const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let data,mode='all',i=0,playing=false,last=performance.now(),lastRange=[],lastPts=[],lastOverlay=[],trace=[];
let lastFeatureMap=new Map(),lastFeatureTimestamp=null,lastCameraTimestamp=null,lastCameraCanvas=document.createElement('canvas');
const world=$('#world'),wc=world.getContext('2d'),camera=$('#camera'),cc=camera.getContext('2d'),chart=$('#chart'),gc=chart.getContext('2d');
const faults={gyroBiasDps:0,gyroNoiseDps:0,cameraDropout:0,rangeDropout:0,cameraDelayMs:0,rangeDelayMs:0};
const SENSOR_POS=[0,0,1];

function fit(c){let r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;c.getContext('2d').setTransform(d,0,0,d,0,0)}
function project(p,w,h){let[x,y,z]=p;return[w*.38+(x-y)*47,h*.83-(z*.92+(x+y)*.19)*53]}
function rot(e,v){let[rx,ry,rz]=e.map(x=>x*Math.PI/180),[x,y,z]=v,cx=Math.cos(rx),sx=Math.sin(rx),cy=Math.cos(ry),sy=Math.sin(ry),cz=Math.cos(rz),sz=Math.sin(rz),X=x,Y=y*cx-z*sx,Z=y*sx+z*cx,X2=X*cy+Z*sy,Y2=Y,Z2=-X*sy+Z*cy;return[X2*cz-Y2*sz,X2*sz+Y2*cz,Z2]}
function add(a,b){return a.map((x,k)=>x+b[k])}function dot(a,b){return a.reduce((s,x,k)=>s+x*b[k],0)}
function terrainBlend(x,y,t){let r=Math.hypot(x,y),a=t.flat_radius||0,b=t.blend_radius||a;if(r<=a)return 0;if(r>=b||b<=a)return 1;let u=(r-a)/(b-a);return u*u*(3-2*u)}
function terrainHeight(x,y){let t=data?.[mode]?.meta?.scene?.terrain;if(!t)return 0;let wave=t.amplitude*(.58*Math.sin(t.wave_x*x)*Math.cos(t.wave_y*y)+.27*Math.sin(1.65*y+.35*x)),r2=(x-t.bump_x)**2+(y-t.bump_y)**2,b=t.bump*Math.exp(-r2/(2*t.bump_sigma**2));return terrainBlend(x,y,t)*(wave+b)}
function normalAt(x,y){let e=.025,a=terrainHeight(x+e,y)-terrainHeight(x-e,y),b=terrainHeight(x,y+e)-terrainHeight(x,y-e),n=[-a/(2*e),-b/(2*e),1],m=Math.hypot(...n);return n.map(v=>v/m)}
function hexRgb(h){h=h.replace('#','');return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]}
function rgbHex(rgb){return'#'+rgb.map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('')}
function shade(hex,k){return rgbHex(hexRgb(hex).map(v=>v*k))}
function lightFactor(normal){let s=data[mode].meta.scene.light,ld=s.direction,m=Math.hypot(...ld),toLight=ld.map(v=>-v/m),d=Math.max(0,dot(normal,toLight));return Math.min(1.25,s.ambient+s.diffuse*d)}
function poly(ctx,pts,fill,stroke=null,alpha=1){if(pts.length<3)return;ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();ctx.moveTo(...pts[0]);pts.slice(1).forEach(p=>ctx.lineTo(...p));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}ctx.restore()}
function depthColor(d){let q=Math.max(0,Math.min(1,(d-.5)/3.5)),h=12+q*205;return`hsl(${h} 86% 52%)`}

function boxGeometry(o){let[cx,cy,cz]=o.center,[sx,sy,sz]=o.size,x0=cx-sx/2,x1=cx+sx/2,y0=cy-sy/2,y1=cy+sy/2,z0=cz-sz/2,z1=cz+sz/2,v=[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]];return{v,faces:[[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7],[4,5,6,7]],normals:[[0,-1,0],[1,0,0],[0,1,0],[-1,0,0],[0,0,1]]}}
function pillarGeometry(o,n=12){let[cx,cy,cz]=o.center,r=o.radius,z0=cz-o.height/2,z1=cz+o.height/2,v=[];for(let k=0;k<n;k++){let a=2*Math.PI*k/n;v.push([cx+r*Math.cos(a),cy+r*Math.sin(a),z0])}for(let k=0;k<n;k++){let a=2*Math.PI*k/n;v.push([cx+r*Math.cos(a),cy+r*Math.sin(a),z1])}let faces=[],normals=[];for(let k=0;k<n;k++){let j=(k+1)%n,a=2*Math.PI*(k+.5)/n;faces.push([k,j,n+j,n+k]);normals.push([Math.cos(a),Math.sin(a),0])}faces.push([...Array(n).keys()].map(k=>n+k));normals.push([0,0,1]);return{v,faces,normals}}
function sceneObjects(){return data[mode].meta.scene.objects.map(o=>({o,g:o.type==='pillar'?pillarGeometry(o):boxGeometry(o)}))}
function axes(e,thick){let w=world.clientWidth,h=world.clientHeight,o=project(SENSOR_POS,w,h);[[.75,0,0],[0,.75,0],[0,0,.75]].forEach((d,j)=>{let q=rot(e,d),p=project(add(SENSOR_POS,q),w,h);wc.lineWidth=thick;wc.beginPath();wc.moveTo(...o);wc.lineTo(...p);wc.strokeStyle=['#d33','#2a7','#36c'][j];wc.stroke()})}
function drawWorldTerrain(){let w=world.clientWidth,h=world.clientHeight,t=data[mode].meta.scene.terrain,step=.45,cells=[];for(let x=t.x_min;x<t.x_max;x+=step)for(let y=t.y_min;y<t.y_max;y+=step){let ps=[[x,y],[x+step,y],[x+step,y+step],[x,y+step]].map(([a,b])=>[a,b,terrainHeight(a,b)]),n=normalAt(x+step/2,y+step/2);cells.push({depth:x+y,pts:ps.map(p=>project(p,w,h)),fill:shade(t.base_color,lightFactor(n))})}cells.sort((a,b)=>a.depth-b.depth).forEach(c=>poly(wc,c.pts,c.fill))}
function drawWorldObjects(){let w=world.clientWidth,h=world.clientHeight;sceneObjects().forEach(({o,g})=>{let faces=g.faces.map((f,k)=>({pts:f.map(j=>g.v[j]),n:g.normals[k],depth:f.reduce((s,j)=>s+g.v[j][0]+g.v[j][1],0)/f.length})).sort((a,b)=>a.depth-b.depth);faces.forEach(f=>poly(wc,f.pts.map(p=>project(p,w,h)),shade(o.color,lightFactor(f.n)),'rgba(35,45,55,.18)'))})}
function drawWorld(r){fit(world);let w=world.clientWidth,h=world.clientHeight,g=wc.createLinearGradient(0,0,0,h);g.addColorStop(0,'#dcecf7');g.addColorStop(1,'#f7f4e8');wc.fillStyle=g;wc.fillRect(0,0,w,h);drawWorldTerrain();drawWorldObjects();if(r.range_world_points&&!r.range_dropped)lastPts=r.range_world_points;wc.fillStyle='#37474f';lastPts.forEach(p=>{let q=project(p,w,h);wc.beginPath();wc.arc(q[0],q[1],2.2,0,7);wc.fill()});axes(r.true_euler,4);axes(r.display_est_euler||r.est_euler,1.5);wc.fillStyle='#172033';wc.font='12px system-ui';wc.fillText('thick axes = truth / thin axes = estimate',12,20)}

function decodeCameraFrame(r){if(!r.camera_rgb_b64||!r.camera_render_size)return false;if(lastCameraTimestamp===r.camera_timestamp)return true;let[rw,rh]=r.camera_render_size,raw=atob(r.camera_rgb_b64),arr=new Uint8ClampedArray(rw*rh*4);for(let p=0,q=0;p<raw.length;p+=3,q+=4){arr[q]=raw.charCodeAt(p);arr[q+1]=raw.charCodeAt(p+1);arr[q+2]=raw.charCodeAt(p+2);arr[q+3]=255}lastCameraCanvas.width=rw;lastCameraCanvas.height=rh;lastCameraCanvas.getContext('2d').putImageData(new ImageData(arr,rw,rh),0,0);lastCameraTimestamp=r.camera_timestamp;return true}
function drawRgbdOverlay(r){if(r.range_camera_overlay&&!r.range_dropped)lastOverlay=r.range_camera_overlay;if(r.range_dropped)return;let w=camera.clientWidth,h=camera.clientHeight;lastOverlay.forEach(([u,v,d,idx])=>{let x=u/640*w,y=v/480*h,c=depthColor(d);cc.strokeStyle='rgba(255,255,255,.95)';cc.lineWidth=2.5;cc.beginPath();cc.arc(x,y,5.5,0,Math.PI*2);cc.stroke();cc.fillStyle=c;cc.beginPath();cc.arc(x,y,4,0,Math.PI*2);cc.fill();if(idx%3===0){cc.fillStyle='rgba(15,23,42,.7)';cc.fillRect(x+6,y-10,38,13);cc.fillStyle='white';cc.font='9px ui-monospace,monospace';cc.fillText(`${d.toFixed(2)}m`,x+8,y)}})}
function drawFeatureTracks(r,w,h){let feats=r.camera_features||[],cur=new Map(feats.map(f=>[f[2],f]));if(lastFeatureTimestamp!==null&&r.camera_timestamp!==lastFeatureTimestamp){cc.save();cc.lineWidth=1.5;cc.strokeStyle='rgba(255,230,70,.78)';for(const[id,f]of cur){let prev=lastFeatureMap.get(id);if(!prev)continue;cc.beginPath();cc.moveTo(prev[0]/640*w,prev[1]/480*h);cc.lineTo(f[0]/640*w,f[1]/480*h);cc.stroke()}cc.restore();lastFeatureMap=cur;lastFeatureTimestamp=r.camera_timestamp}else if(lastFeatureTimestamp===null){lastFeatureMap=cur;lastFeatureTimestamp=r.camera_timestamp}for(const[id,f]of cur){let x=f[0]/640*w,y=f[1]/480*h;cc.strokeStyle='white';cc.lineWidth=2.5;cc.beginPath();cc.arc(x,y,5,0,Math.PI*2);cc.stroke();cc.fillStyle='#1565c0';cc.beginPath();cc.arc(x,y,3.4,0,Math.PI*2);cc.fill();cc.fillStyle='#071526';cc.font='bold 9px system-ui';cc.fillText('#'+id,x+6,y-5)}}
function drawCamera(r){fit(camera);let w=camera.clientWidth,h=camera.clientHeight;cc.fillStyle='#e8edf3';cc.fillRect(0,0,w,h);let ok=decodeCameraFrame(r);if(ok){cc.imageSmoothingEnabled=false;cc.drawImage(lastCameraCanvas,0,0,w,h)}else{cc.fillStyle='#64748b';cc.font='14px system-ui';cc.fillText('No camera frame in this fusion mode',16,28)}drawRgbdOverlay(r);if(!r.camera_dropped&&r.camera_features)drawFeatureTracks(r,w,h);if(r.camera_dropped){cc.fillStyle='rgba(180,83,9,.9)';cc.fillRect(12,12,170,28);cc.fillStyle='white';cc.font='bold 14px system-ui';cc.fillText('CAMERA DROPOUT',22,31)}if(r.camera_timestamp!=null){let dt=r.range_camera_dt_ms;cc.fillStyle='rgba(15,23,42,.78)';cc.fillRect(10,h-42,300,32);cc.fillStyle='white';cc.font='11px system-ui';cc.fillText(`Camera t=${r.camera_timestamp.toFixed(3)} s · Harris features ${(r.camera_features||[]).length}`,17,h-27);cc.fillText(`Range↔Camera Δt=${Number.isFinite(dt)?dt.toFixed(1):'—'} ms`,17,h-14)}}

function drawDepth(r){if(r.range_distances&&!r.range_dropped)lastRange=r.range_distances;$('#depth').innerHTML='';for(let k=0;k<64;k++){let d=lastRange[k],el=document.createElement('div');if(r.range_dropped){el.style.background='#fee2e2';el.textContent='×'}else if(d==null){el.style.background='#e8edf4';el.textContent='—'}else{el.style.background=depthColor(d);el.style.color='white';el.textContent=d.toFixed(2)}$('#depth').appendChild(el)}}
function angleErr(a,b){let d=a.map((x,k)=>x-b[k]);return Math.sqrt(d.reduce((s,x)=>s+x*x,0))}
function drawState(r){let eul=r.display_est_euler||r.est_euler,n=['Roll','Pitch','Yaw'];$('#state').innerHTML=n.map((x,k)=>`<div class="metric">${x}<b>${eul[k].toFixed(2)}°</b><small>true ${r.true_euler[k].toFixed(2)}°</small></div>`).join('')+`<div class="metric">Displayed error<b>${angleErr(eul,r.true_euler).toFixed(3)}°</b></div>`;let e=r.event,delay=e.delayed_from_t!=null?`<br><span class="warn">Delayed observation from t=${e.delayed_from_t.toFixed(3)} s</span>`:'';$('#event').innerHTML=`<strong>Latest update: ${e.kind.toUpperCase()}</strong><br>Residual: ${e.residual_deg.toFixed(3)}° → Applied correction: ${e.correction_deg.toFixed(3)}°${delay}`;let m=data[mode].metrics;$('#metrics').textContent=`Python reference: RMSE ${m.orientation_rmse_deg.toFixed(3)}° / MAE ${m.orientation_mae_deg.toFixed(3)}° / Max ${m.orientation_max_deg.toFixed(3)}°`}
function drawChart(){fit(chart);let w=chart.clientWidth,h=chart.clientHeight,colors={imu_only:'#9aa5b1',imu_camera:'#2962ff',imu_range:'#1b8a5a',all:'#d84315'},max=1;Object.values(data).forEach(d=>d.records.forEach(r=>max=Math.max(max,r.error_deg)));gc.clearRect(0,0,w,h);Object.entries(data).forEach(([key,d])=>{gc.strokeStyle=colors[key];gc.lineWidth=key===mode?3:1.2;gc.globalAlpha=key===mode?1:.55;gc.beginPath();d.records.forEach((r,k)=>{let x=36+k/(d.records.length-1)*(w-48),y=h-24-r.error_deg/max*(h-40);k?gc.lineTo(x,y):gc.moveTo(x,y)});gc.stroke()});gc.globalAlpha=1}
function addTrace(r){let e=r.event,bits=[`t=${r.t.toFixed(3)}`,e.kind.toUpperCase(),`res=${e.residual_deg.toFixed(3)}°`,`corr=${e.correction_deg.toFixed(3)}°`];if(r.camera_timestamp!=null)bits.push(`cam=${r.camera_timestamp.toFixed(3)}`);if(r.range_timestamp!=null)bits.push(`range=${r.range_timestamp.toFixed(3)}`);trace.unshift(bits.join(' | '));trace=trace.slice(0,80);$('#trace').innerHTML=trace.map(x=>`<div>${x}</div>`).join('')}
function render(addEvent=false){let base=data[mode].records[i],r=ExperimentModel.apply(base,i,faults,data[mode].records);drawWorld(r);drawCamera(r);drawDepth(r);drawState(r);drawChart();if(addEvent)addTrace(r);$('#status').textContent=`t=${r.t.toFixed(3)} s / ${data[mode].metrics.duration_s.toFixed(1)} s`}
function step(n){i=Math.max(0,Math.min(data[mode].records.length-1,i+n));render(true)}
$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));i=Math.min(i,data[mode].records.length-1);lastRange=[];lastPts=[];lastOverlay=[];trace=[];lastFeatureMap=new Map();lastFeatureTimestamp=null;lastCameraTimestamp=null;render(true)});
$('#prev').onclick=()=>step(-1);$('#next').onclick=()=>step(1);$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'❚❚ Pause':'▶ Play'};
const bind=(id,key,out,fmt)=>{$('#'+id).oninput=e=>{faults[key]=parseFloat(e.target.value);$('#'+out).textContent=fmt(faults[key]);render(false)}};
bind('gyroBias','gyroBiasDps','vBias',v=>`${v.toFixed(2)} °/s`);bind('gyroNoise','gyroNoiseDps','vNoise',v=>`${v.toFixed(2)} °`);bind('camDrop','cameraDropout','vCamDrop',v=>`${v.toFixed(0)}%`);bind('rangeDrop','rangeDropout','vRangeDrop',v=>`${v.toFixed(0)}%`);bind('camDelay','cameraDelayMs','vCamDelay',v=>`${v.toFixed(0)} ms`);bind('rangeDelay','rangeDelayMs','vRangeDelay',v=>`${v.toFixed(0)} ms`);
$('#resetFaults').onclick=()=>{[['gyroBias'],['gyroNoise'],['camDrop'],['rangeDrop'],['camDelay'],['rangeDelay']].forEach(([id])=>{$('#'+id).value=0;$('#'+id).dispatchEvent(new Event('input'))});trace=[];render(true)};
function loop(t){if(playing&&data){let inc=Math.max(1,Math.round((t-last)/1000*parseFloat($('#speed').value)*data[mode].meta.imu_hz));step(inc);if(i>=data[mode].records.length-1)playing=false}last=t;requestAnimationFrame(loop)}
fetch('data/demo.json').then(r=>r.json()).then(x=>{data=x;render(true);requestAnimationFrame(loop)}).catch(e=>$('#status').textContent='demo.json load failed: '+e);
window.addEventListener('resize',()=>data&&render(false));
